export default {
    antenna: [
        "4Player Network",
        "8-Ball",
        "9GAG",
        "AbleGamers",
        "Achievement Hunter",
        "Afghanistan",
        "Aiobahn",
        "Albania",
        "Algeria",
        "Alien",
        "American Samoa",
        "Andorra",
        "Angola",
        "Angry Army",
        "Anguilla",
        "Anna Yvette",
        "Anne Munition",
        "Antigua&Barbuda",
        "Arachnotenna",
        "Argentina",
        "Armenia",
        "Aruba",
        "Atlanta Hawks",
        "Australia",
        "Austria",
        "Azerbaijan",
        "Bad Computer",
        "Bahamas",
        "Bahrain",
        "Balloon Dog",
        "Bangladesh",
        "Barbados",
        "Batman",
        "Belarus",
        "Belgium",
        "Belize",
        "Benin",
        "Bermuda",
        "Bhutan",
        "Blacklight",
        "Blacklight: Retribution",
        "Blue Chequered Flag",
        "Bolivia",
        "Bomb Pole",
        "Bosnia and Herzegovina",
        "Boston Celtics",
        "Botswana",
        "Brazil",
        "British Virgin Islands",
        "Brooklyn Nets",
        "Brunei",
        "Bubble Wand",
        "Bulgaria",
        "Burkina Faso",
        "Burma",
        "Burundi",
        "Calavera",
        "Calculated",
        "Cambodia",
        "Cameroon",
        "Camo Flag",
        "Canada",
        "Candle",
        "Candy Cane",
        "Cape Verde Islands",
        "Cayman Islands",
        "Central Africa Republic",
        "Chad",
        "Charlotte Hornets",
        "Chicago Bulls",
        "Chick Magnet",
        "Chile",
        "China",
        "Chinese Taipei",
        "Chivalry - Agatha Knights",
        "Chivalry - Mason Order",
        "Cleveland Cavaliers",
        "Colombia",
        "Community Flags",
        "Community",
        "Comoros",
        "Congo DR",
        "Congo",
        "Cook Islands",
        "Costa Rica",
        "Côte d'Ivoire",
        "Country Flags",
        "Croatia",
        "Cuba",
        "Cuckoo Clock",
        "Cupcake",
        "Curacao",
        "Cyprus",
        "Czech Republic",
        "Dallas Mavericks",
        "Dandelion Seed",
        "Darren Styles",
        "Dave's Bread",
        "Day TV",
        "deadmau5",
        "Denmark",
        "Denver Nuggets",
        "Destructoid",
        "Detroit Pistons",
        "Dion Timmer",
        "Disco Ball",
        "Disconnect",
        "Discord",
        "Div",
        "Djibouti",
        "Dollar Sign",
        "Dominica",
        "Dominican Republic",
        "Donut",
        "Dougal",
        "Duumu",
        "Dying Light",
        "Dying Light-Gas Tank",
        "East Timor",
        "Easter Egg",
        "Ecuador",
        "Edge Of Space",
        "Egypt",
        "El Salvador",
        "EMD1",
        "England",
        "Equatorial Guinea",
        "Eritrea",
        "ESL Champ",
        "ESL",
        "Estonia",
        "Ethiopia",
        "Euro Truck Simulator Rig",
        "Eyeball",
        "Falkland Islands",
        "Fallout-Vault Boy",
        "Faroe Islands",
        "Fenix Rage",
        "Fiji",
        "Finland",
        "Flower-Daisy",
        "Flower-Orchid",
        "Flower-Rose",
        "Flower-Sunflower",
        "Flower-Tulip",
        "Foam Finger",
        "France",
        "Funhaus",
        "Fuzzy Brute",
        "Fuzzy Skull",
        "Fuzzy Vamp",
        "Gabon",
        "Gambia",
        "Gamespot",
        "Gammer",
        "Genie Lamp",
        "Georgia",
        "Germany",
        "Gfinity",
        "Ghana",
        "Giant Panda",
        "Gibraltar",
        "Gingerbread Man",
        "Goat Simulator-G2",
        "Goat Simulator-Goatenna",
        "Gold Glove",
        "Gold Nugget",
        "Golden State Warriors",
        "Greece",
        "Grenada",
        "Guam",
        "Guatemala",
        "Guinea",
        "Guyana",
        "Haiti",
        "Harpoon",
        "Headlander-Starcophagus",
        "Heart",
        "Holiday Gift",
        "Holiday Stocking",
        "Honduras",
        "Hong Kong",
        "Horseshoe",
        "Hot Dog",
        "Hot Wheels 50th",
        "Hot Wheels",
        "Houston Rockets",
        "Hula Girl",
        "Hungary",
        "Iceland",
        "IGN",
        "India",
        "Indiana Pacers",
        "Indonesia",
        "Infected Mushroom",
        "InGen",
        "Instinct",
        "Intercom",
        "Iran",
        "Iraq",
        "Ireland",
        "Isle Of Man",
        "Israel",
        "Italy",
        "itmeJP",
        "J!NX",
        "Jamaica",
        "Japan",
        "Jolly Roger",
        "Jon Sandman",
        "Jordan",
        "Jurassic Park",
        "Jurassic World",
        "Kazakhstan",
        "Kenya",
        "Kiribati",
        "Koinobori",
        "Kosovo",
        "Koven",
        "Kuwait",
        "Kyrgyzstan",
        "Laos",
        "Latvia",
        "Lebanon",
        "Lesotho",
        "Liberia",
        "Libya",
        "Lightning Bolt",
        "Linguist",
        "LIRIK",
        "Lithuania",
        "Lollipop",
        "lolRenaynay",
        "Loot Crate",
        "Los Angeles Clippers",
        "Los Angeles Lakers",
        "Luxembourg",
        "Macaron",
        "Macau",
        "Macedonia",
        "Madagascar",
        "Mage Glass I",
        "Mage Glass II",
        "Mage Glass III",
        "Malawi",
        "Malaysia",
        "Maldives",
        "Mali",
        "Malta",
        "Marshall Islands",
        "Mauritania",
        "Mauritius",
        "Memphis Grizzlies",
        "Mexico",
        "Miami Heat",
        "Micronesia",
        "Milwaukee Bucks",
        "Minnesota Timberwolves",
        "MLG",
        "Moai",
        "Moderator",
        "Moldova",
        "Monaco",
        "Mongolia",
        "Monstercat",
        "Montenegro",
        "Montserrat",
        "Morocco",
        "Morty",
        "Mozambique",
        "Mr Toasty",
        "Muzzy",
        "Namibia",
        "Nauru",
        "NBA Flags",
        "NBA",
        "NeoGAF",
        "Nepal",
        "Netherlands",
        "New Caledonia",
        "New Orleans Pelicans",
        "New York Knicks",
        "New Zealand",
        "Nicaragua",
        "Nigeria",
        "NoClip",
        "North Korea",
        "North Mariana Islands",
        "Northern Ireland",
        "Norway",
        "Nutcracker",
        "NVIDIA SHIELD",
        "NVIDIA",
        "NZXT",
        "Oddworld-Abe",
        "Oddworld-Molluck",
        "Oddworld-Necrum",
        "Oddworld-RuptureFarms",
        "Oklahoma City Thunder",
        "Oman",
        "Operation Sports",
        "Orlando Magic",
        "Pakistan",
        "Palau",
        "Palestine",
        "Panama",
        "Panic Button",
        "Papua New Guinea",
        "Paraguay",
        "Parrot",
        "PAX",
        "PC Gamer",
        "Peace Sign",
        "Pegboard Nerds",
        "Penny Arcade",
        "Peppermint",
        "Peru",
        "Philadelphia 76ers",
        "Philippines",
        "Phoenix Suns",
        "Piñata",
        "Pixel Terror",
        "Poland",
        "Polaris",
        "Portal-Aperture Laboratories",
        "Portal-Cake Sticker",
        "Portal-Companion Cube",
        "Portal-PotatOS",
        "Portal-Wheatley",
        "Portland Trail Blazers",
        "Portugal",
        "Protostar",
        "Psyonix",
        "Puerto Rico",
        "Puntland",
        "Qatar",
        "Radioactive",
        "Rainbow Flag",
        "Razer",
        "Reddit Snoo",
        "Reddit",
        "Republic of Niger",
        "Retro Ball - Urban",
        "Retro Ball - Utopia",
        "Retro Ball - Wasteland",
        "Réunion",
        "Rick",
        "RL Garage",
        "RLCS",
        "Rocket Beans TV",
        "Rocket",
        "Romania",
        "Rooster Teeth",
        "Rubber Duckie",
        "Rwanda",
        "S Watercolour",
        "Sacramento Kings",
        "Safety Flag",
        "Saint Kitts&Nevis",
        "Saint Lucia",
        "Saint Vincent",
        "Samoa",
        "San Antonio Spurs",
        "San Marino",
        "Sao Tome",
        "SARPBC-10",
        "Satellite",
        "Saturn",
        "Saudi Arabia",
        "Saudi Gamer",
        "Scotland",
        "ScrewAttack",
        "SDMN FC",
        "Seastar",
        "Senegal",
        "Serbia",
        "Serious Gaming",
        "Seychelles",
        "Shacknews",
        "Shadow Witch",
        "Shadowgate",
        "Sierra Leone",
        "Siiick Reads",
        "Singapore",
        "Skull",
        "Skyelle",
        "Slippy",
        "Slovakia",
        "Slovenia",
        "Smiley Face",
        "Snowman",
        "Soccer Ball",
        "Solomon Islands",
        "Somalia",
        "Somaliland",
        "Something Awful",
        "Soupandreas",
        "South Africa",
        "South Korea",
        "South Sudan",
        "Spain",
        "Spartan Sam",
        "Spooky1611",
        "Sri Lanka",
        "Star",
        "Stephen Walking",
        "Stonebank",
        "Strike Vector EX",
        "Sudan",
        "Sundial",
        "Superman",
        "Suriname",
        "Swaziland",
        "Sweden",
        "Sweet Tooth",
        "Switzerland",
        "Syria",
        "Tahiti",
        "Tajikistan",
        "Tanzania",
        "Team Fat",
        "Team PowA",
        "Tennis Ball",
        "Thailand",
        "The Attack",
        "The Game Awards-Logo",
        "The Game Awards-Statue",
        "Togo",
        "Tokyo Machine",
        "Tonga",
        "Toronto Raptors",
        "Tourney Champ",
        "Treasure Hunt",
        "Trident",
        "Trinidad and Tobago",
        "Tunisia",
        "Turkey",
        "Turkmenistan",
        "Turks&Caicos",
        "Tuvalu",
        "Twitch",
        "UFO",
        "Uganda",
        "Ukraine",
        "Uncaged Cat",
        "Uncaged",
        "United Arab Emirates",
        "United Kingdom",
        "United States",
        "Unreal Frag Center",
        "Unreal Tournament - Flak Shell",
        "Unreal Tournament - Red",
        "Unreal Tournament (Classic)",
        "Unreal Tournament 2004",
        "Unreal Tournament",
        "Unreal Tournament-Blue",
        "Unreal",
        "Uruguay",
        "US Virgin Islands",
        "Utah Jazz",
        "Uzbekistan",
        "Vanuatu",
        "Vatican City",
        "Venezuela",
        "Venus Flytrap",
        "Video Games",
        "Vietnam",
        "Vikkstar",
        "Waffle",
        "Wales",
        "Warframe",
        "Warframe-Chroma",
        "Warframe-Excalibur",
        "Warframe-Loki",
        "Warm Watermelon",
        "Washington Wizards",
        "Western Sahara",
        "White Flag",
        "Witcher Medallion",
        "Wonder Woman",
        "Worms W.M.D",
        "Worms W.M.D. Grenade",
        "WWE Monday Night RAW",
        "WWE NXT",
        "WWE SmackDown Live",
        "WWE WrestleMania 34",
        "WWE",
        "X Games",
        "Yemen",
        "YouTube Gaming",
        "Zambia",
        "Zimbabwe"        
    ],
    body: [
        "'70 Dodge Charger R/T",
        "'89 Batmobile",
        "'99 Nissan Skyline GT-R R34",
        "Aftershock",
        "Animus GP",
        "Armadillo",
        "Backfire",
        "Batmobile",
        "Bone Shaker",
        "Breakout Type-S",
        "Breakout",
        "Centio V17",
        "Cyclone",
        "DeLorean Time Machine",
        "Dominus GT",
        "Dominus",
        "Endo",
        "Esper",
        "Fast 4WD",
        "Gazella GT",
        "Gizmo",
        "Grog",
        "Hogsticker",
        "Hotshot",
        "Ice Charger",
        "Imperator DT5",
        "Jäger 619 RS",
        "Jurassic Jeep® Wrangler",
        "Mantis",
        "Marauder",
        "Mario NSR",
        "Masamune",
        "Maverick G1",
        "Maverick GXT",
        "Maverick",
        "Merc",
        "MR11",
        "Mystery Item",
        "Octane ZSR",
        "Octane",
        "Paladin",
        "Proteus",
        "Ripper",
        "Road Hog XL",
        "Road Hog",
        "Samurai",
        "Samus's Gunship",
        "Scarab",
        "Sweet Tooth",
        "Takumi RX-T",
        "Takumi",
        "The Dark Knight Rises Tumbler",
        "Triton",
        "Twin Mill III",
        "Twinzer",
        "Venom",
        "Vulcan",
        "Werewolf",
        "X-Devil Mk2",
        "X-Devil",
        "Zippy"
    ],
    "rocket boost": [
        "'89 Batmobile",
        "Accelerato",
        "Batmobile",
        "Battle-Stars",
        "Blamite Overthruster",
        "Blast Ray",
        "Bubbles",
        "Burnout",
        "Candy Corn",
        "Cirrus",
        "Cloudburst I",
        "Cloudburst II",
        "Cloudburst III",
        "Cold Fusion",
        "Comet",
        "Confetti",
        "Dark Matter",
        "Datastream",
        "Enchanter",
        "Feather",
        "Flamethrower Blue",
        "Flamethrower Green",
        "Flamethrower Pink",
        "Flamethrower Purple",
        "Flamethrower Red",
        "Flamethrower Yellow",
        "Flamethrower",
        "Flowers",
        "Fractal Fire",
        "Frostbite",
        "Geo Soul",
        "Gold Rush",
        "Hearts",
        "Helios",
        "Hexphase",
        "Hot Rod",
        "Hydro",
        "Hypernova",
        "Imulsion",
        "Ink",
        "Interdimensional GB",
        "Ion Green",
        "Ion Pink",
        "Ion Purple",
        "Ion Red",
        "Ion Yellow",
        "Ion",
        "Lightning Yellow",
        "Lightning",
        "Magic Missile",
        "Magmus",
        "Money",
        "Neo-Thermal",
        "Netherworld",
        "Nitrous",
        "Nuts & Bolts",
        "OutaTime",
        "Overcharge",
        "Pixel Fire",
        "Plasma",
        "Polygonal",
        "Popcorn",
        "Portal - Conversion Gel",
        "Portal - Propulsion Gel",
        "Portal - Repulsion Gel",
        "Power-Shot",
        "Proton",
        "Rainbow",
        "Sacred",
        "Sandstorm",
        "Scary Pumpkin",
        "Season 2 - Challenger",
        "Season 2 - Champion",
        "Season 2 - Prospect",
        "Season 2 - Star",
        "Season 8 - Bronze",
        "Season 8 - Champion",
        "Season 8 - Diamond",
        "Season 8 - Gold",
        "Season 8 - Platinum",
        "Season 8 - Silver",
        "Slime",
        "Snowflakes",
        "Sparkles",
        "Speed Force",
        "Springtime Flowers",
        "Standard Blue",
        "Standard Green",
        "Standard Pink",
        "Standard Purple",
        "Standard Yellow",
        "Standard",
        "Sun Ray",
        "Super Star",
        "Sweet Tooth",
        "Tachyon",
        "Taco",
        "The Dark Knight Rises Tumbler",
        "Thermal Blue",
        "Thermal Green",
        "Thermal Pink",
        "Thermal Purple",
        "Thermal Yellow",
        "Thermal",
        "Toon Sketch",
        "Toon Smoke",
        "Torrent",
        "Treasure",
        "Trinity",
        "Tsunami Beam",
        "UV Turret",
        "Virtual Wave",
        "Wave Beam",
        "Winter Storm",
        "Xenosplash",
        "Xmas",
        "Yuletide"
    ],
    decal: [
        "20XX",
        "2Bold",
        "2Cool",
        "2Tuff",
        "Afterlife",
        "Alameda Twin",
        "Animus GP: Peacock",
        "Anticlipse",
        "Anubis",
        "Aquaman",
        "Aqueous",
        "ARC",
        "Arcadia",
        "Arcana",
        "Armada",
        "Arrowhead",
        "Arsenal",
        "Athena",
        "AWD",
        "Baller",
        "Batman",
        "Battleworn",
        "Big Buck",
        "Big Scratches",
        "Biomass",
        "Blackwork",
        "Block Trim",
        "Bomani",
        "Bomber",
        "Bone Jack",
        "BOO!",
        "Boo-ya!",
        "Breakout: 9 Lives",
        "Breakout: Astaroth",
        "Breakout: Bobcat",
        "Breakout: CRL Western",
        "Breakout: Nice Shot",
        "Breakout: Ripped Comic",
        "Breakout: Sneaky Slither",
        "Bubbly",
        "Buzz Kill",
        "Caboodle",
        "Callous Bros.",
        "Callous",
        "Camo",
        "Carbonated",
        "CDXL",
        "Chameleon",
        "Chaser",
        "Christmas Tree",
        "Chusho",
        "Circuit Pro",
        "Clean Cut",
        "Cobra",
        "Cold Front",
        "Cold Sweater",
        "Combat",
        "Combo",
        "Copycat",
        "Crash Dive",
        "Crazy Sandwich",
        "Crazy-8",
        "Critters",
        "Cryo-Flames",
        "Cupcake",
        "Cuttle Time",
        "Cyborg",
        "Cyclone: Bat Boy",
        "Cyclone: Flames",
        "Cyclone: L-ITA 99",
        "Cyclone: Sliver",
        "Cyclone: Stripes",
        "Cyclone: Whiteout",
        "Cyclops",
        "Cyrus",
        "Daddy-O",
        "Debugged",
        "Derby Girl",
        "Dissolver",
        "Distortion",
        "DJ Sushi",
        "Dominus: CRL Eastern",
        "Dominus: CRL Southern",
        "Dominus: Dot Matrix",
        "Dominus: Proptosis",
        "Dominus: RC Rivals",
        "Dominus: Savage",
        "Dominus: Templar",
        "Dot Matrix",
        "Dot Rush",
        "Dots",
        "Dragon Lord",
        "Dune Racer",
        "Dyno",
        "Echo-Pulse",
        "Egged",
        "Euphoria",
        "Falchion",
        "Fantasmo",
        "Fast 4WD: 50th Anniversary",
        "Fast 4WD: Diecast",
        "Fast 4WD: Hot Wheels Race Team",
        "Fast 4WD: Sleek",
        "Fathom",
        "Feral",
        "Fire God",
        "Flagman",
        "Flames",
        "Flex",
        "Flower Power",
        "Froggy",
        "Fugu",
        "Funny Book",
        "Funnybook",
        "Gaki",
        "Gale-Fire",
        "Gazella GT: 50th Anniversary",
        "Gazella GT: Diecast",
        "Gazella GT: Hot Wheels Race Team",
        "Gazella GT: Sleek",
        "Gigapede",
        "Glyphtrix",
        "Gobo",
        "Good Graces",
        "Green Arrow",
        "Green Lantern",
        "Griffon",
        "Hammerhead",
        "Hearts",
        "Heatwave",
        "Heiwa",
        "Hexed",
        "Hip-Hop",
        "Hi-Tech",
        "Holiday Deco",
        "Home Stretch",
        "Horus",
        "Humble Pie",
        "Hyper",
        "Hyper-Flight",
        "Inferno",
        "Inked",
        "Interceptor",
        "Iris",
        "Jäger 619 RS: Shark Tooth",
        "Jäger 619 RS: StarLighter",
        "Javelin",
        "Jetstream",
        "Jiangshi",
        "Junk Food",
        "Kaiju",
        "Kaleidoscope",
        "Kawaii",
        "Kaze",
        "Kilowatt",
        "Kraken",
        "Labyrinth",
        "Ladybug",
        "Leopard",
        "Lepus",
        "Leviathan",
        "Lightning",
        "L-ITA 99",
        "Lone Wolf",
        "Machina",
        "Mainframe",
        "Makai",
        "Maximon",
        "Maxx",
        "MDGA",
        "Mean Streak",
        "Medic",
        "Merc: B.B. Wolf",
        "MG-88",
        "Midnight D",
        "Min-Spec",
        "MiNT",
        "MIRV",
        "Mister Monsoon",
        "Mobo",
        "Modus Bestia",
        "Mondo",
        "Monstercat",
        "Monza",
        "Mosher",
        "Motor Monster",
        "Mouse Cat",
        "MR11: 50th Anniversary",
        "MR11: Diecast",
        "MR11: Hot Wheels Race Team",
        "MR11: Sleek",
        "Muerto",
        "Mummified",
        "Mystery Universal Decal",
        "Namesake",
        "Narwhal",
        "NBP",
        "Necro",
        "Neo",
        "Nine Lives",
        "NNTR",
        "Ockie",
        "Octane ZSR: Mechaceph",
        "Octane: Chantico",
        "Octane: CRL Northern",
        "Octane: Dr. Thrash",
        "Octane: Island King",
        "Octane: Nice Shot",
        "Octane: Noooo!",
        "Octane: RC Rivals",
        "Octane: Space Cadet",
        "Octane: Turtle Tribe",
        "Odd Fish",
        "Oni",
        "Otaku",
        "Overhaul",
        "Overline",
        "Parallax",
        "Partly Cloudy",
        "Party-Chan",
        "Peace",
        "Pegasus",
        "Playtime",
        "Polar Force",
        "Pollinator",
        "Pollo Caliente",
        "Primo",
        "Pro",
        "Pro-Street",
        "Protractor",
        "Pyro",
        "Python",
        "Racer",
        "Rad Reindeer",
        "Radium",
        "Ragnarok",
        "Rakugaki",
        "Rally",
        "Reiko",
        "Righteous Sun",
        "Ripped Comic",
        "RLCS",
        "Road Rage",
        "Roadkill",
        "Roasted",
        "Rockat",
        "Rose King",
        "Royal Tyrant",
        "Royalty",
        "Ruffian",
        "Safari",
        "Sara Skinner",
        "Scorpions",
        "Seismic",
        "Shank",
        "ShapeRacer",
        "Shapeshifter",
        "Shibuya",
        "Shisa",
        "Shockwave",
        "Shot Fox",
        "Sinclair",
        "Skullface",
        "Skulls",
        "Slimed",
        "Slimline",
        "Slipstream",
        "Smore'd",
        "Snakeskin",
        "Space Trip",
        "Space Worm",
        "Spatter",
        "Spectre",
        "Speedster",
        "Spikes",
        "Splashback",
        "Splatter",
        "Star Swash",
        "Staredown",
        "Stars",
        "Starstruck",
        "Sticker Bomb",
        "Stitches",
        "Storm Warning",
        "Storm Watch",
        "Streamline",
        "Stripe Racer",
        "Stripes",
        "Suji",
        "Sunburst",
        "Sundae",
        "Super F3",
        "Super RX-T",
        "Superman",
        "Swirls",
        "SWT-T",
        "Tagged",
        "Tats",
        "Tech",
        "Techno",
        "Thanatos",
        "The Clutch",
        "The Flash",
        "The Summit",
        "Thunderspeck",
        "Tiger Shark",
        "Tiger Tiger",
        "Tiger",
        "Tora",
        "Trace Racer",
        "Tribal",
        "Trigon",
        "Turbo",
        "Twisted Tree",
        "Unmasked",
        "Uproar",
        "Vagabond",
        "Vector",
        "Warlock",
        "Wheelman",
        "Whizzle",
        "Widow's Web",
        "Wildfire",
        "Windswept",
        "Wings",
        "Wonder Woman",
        "X-Devil: Devil's Advocate",
        "X-Devil: Dot Matrix",
        "XVI",
        "XVIII",
        "Zhangtek"
    ],
    "engine audio": [
        "'70 Dodge Charger R/T",
        "'89 Batmobile",
        "'99 Nissan Skyline GT-R R34",
        "Aftershock v2",
        "Aftershock",
        "Animus GP",
        "Armadillo",
        "Batmobile",
        "Bone Shaker",
        "Breakout Type-S v2",
        "Breakout Type-S",
        "Centio V17",
        "Cyclone",
        "DeLorean Time Machine",
        "Dominus GT v2",
        "Dominus GT",
        "Dominus",
        "Endo",
        "Esper",
        "Fast 4WD",
        "Gazella GT",
        "Go-Kart",
        "Grog",
        "HogSticker",
        "Ice Charger",
        "Imperator DT5",
        "Jäger 619 RS",
        "Jurassic Jeep® Wrangler",
        "Mantis",
        "Marauder v2",
        "Marauder",
        "Masamune",
        "Maverick",
        "Motormouth",
        "MR11",
        "Muscle Car",
        "NSR",
        "Octane ZSR v2",
        "Octane ZSR",
        "OEM-A v2",
        "OEM-A",
        "OEM-B v2",
        "OEM-B",
        "OEM-C v2",
        "OEM-C",
        "OEM-D v2",
        "OEM-D",
        "Proteus v2",
        "Proteus",
        "Ripper",
        "Road Hog XL v2",
        "Road Hog XL",
        "Samurai",
        "Samus's Gunship",
        "Scarab",
        "Sweet Tooth",
        "Takumi RX-T v2",
        "Takumi RX-T",
        "Takumi",
        "The Dark Knight Rises Tumbler",
        "Triton v2",
        "Triton",
        "Twin Mill III",
        "Twinzer",
        "Vulcan",
        "Werewolf",
        "X-Devil Mk2 v2",
        "X-Devil Mk2",
        "Zippy"
    ],
    "goal explosion": [
        "Atomizer",
        "Ballistic",
        "Beach Party",
        "Butterflies",
        "Classic",
        "Dueling Dragons",
        "Electroshock",
        "Fireworks",
        "Happy Holidays",
        "Hellfire",
        "Hot Wheels",
        "Juiced",
        "Party Time",
        "Poly Pop",
        "Popcorn",
        "Reaper",
        "Singularity",
        "Standard Green",
        "Standard Orange",
        "Standard Pink",
        "Standard Purple",
        "Striker Legend",
        "Striker Pro",
        "Striker",
        "Sub-Zero",
        "Supernova I",
        "Supernova II",
        "Supernova III",
        "T. rex",
        "Toon",
        "Vampire Bat"   
    ],
    "paint finish": [
        "Anodized",
        "Brushed Metal",
        "Burlap",
        "Canvas",
        "Circuit Board",
        "Cookie Dough",
        "Corroded Metal",
        "Furry",
        "Glossy",
        "Knitted Yarn",
        "Matte",
        "Metallic (Rough)",
        "Metallic (Smooth)",
        "Metallic Flake",
        "Metallic Pearl (Smooth)",
        "Metallic Pearl",
        "Metallic",
        "Moon Rock",
        "Pearlescent (Matte)",
        "Pearlescent",
        "Semigloss",
        "Skullcap",
        "Stainless Steel",
        "Sun-Damaged",
        "Toon Matte",
        "Wood",
        "Zebra"
    ],
    "player banner": [
        "Ball King",
        "Battle-Cars Anniversary",
        "Beaten Egg",
        "Birthday Bash",
        "Blast Off",
        "Block",
        "Blueprint",
        "Burnout",
        "Calculated",
        "Call Sign RL",
        "Coral",
        "Crisscross",
        "CRL Eastern",
        "CRL Northern",
        "CRL Southern",
        "CRL Western",
        "Crystal",
        "DC Comics",
        "Dead Serious",
        "Dendritic",
        "Doughnut Eater",
        "Feathered",
        "Game On",
        "Hoagie",
        "Holiday Gifts",
        "Hot Wheels 50th",
        "Howler",
        "Ice Pop",
        "Ishihara",
        "Island Scales",
        "Jurassic Park",
        "Jurassic World",
        "Lift-Off",
        "Migraine",
        "Moai",
        "Mrs. Avocado",
        "Nice Slice",
        "Old Flame",
        "Pigeon",
        "Psyonix",
        "RL Esports",
        "Rocket Labs",
        "S. Watercolour",
        "Salty",
        "Season 5 - Bronze (Dragon)",
        "Season 5 - Bronze",
        "Season 5 - Champion (Dragon)",
        "Season 5 - Champion",
        "Season 5 - Diamond (Dragon)",
        "Season 5 - Diamond",
        "Season 5 - Gold (Dragon)",
        "Season 5 - Gold",
        "Season 5 - Grand Champion (Dragon)",
        "Season 5 - Grand Champion",
        "Season 5 - Platinum (Dragon)",
        "Season 5 - Platinum",
        "Season 5 - Silver (Dragon)",
        "Season 5 - Silver",
        "Season 7 - Tier 1",
        "Season 7 - Tier 2",
        "Season 7 - Tier 3",
        "Season 7 - Tier 4",
        "Season 7 - Tier 5",
        "Season 7 - Tier 6",
        "Season 7 - Tier 7",
        "Shark Attack",
        "Sharp Flames",
        "Shattered",
        "Shooting Star",
        "S'mored",
        "Soccar Nebula",
        "Soccer Ball",
        "Soccer Splash",
        "Solar System",
        "Standard",
        "Starbase ARC",
        "Sushi Roll",
        "Taxi",
        "Topographic",
        "Trash It!",
        "Triangle",
        "Triplicate",
        "Turtle",
        "Unicorn",
        "Vice",
        "Winning Streak",
        "Winter's Warmth",
        "WWE Monday Night RAW",
        "WWE NXT",
        "WWE SmackDown Live!",
        "WWE WrestleMania 34",
        "WWE",
        "Zombie"
    ],
    toppers: [
        "Angel Wings",
        "Antlers",
        "Baseball Cap (B)",
        "Baseball Cap (F)",
        "Beret",
        "Biker Cap",
        "Birthday Cake",
        "Black Market Preview",
        "Blitzen",
        "Bobby Helmet",
        "Bone King",
        "Boombox",
        "Bowler",
        "Breakout: What A Save!",
        "Brodie Helmet",
        "Brünnehilde",
        "Bunny Ears",
        "Butterfly",
        "Buzzer",
        "Bycocket",
        "Campaign Hat",
        "Captain's Hat",
        "Catfish",
        "Cattleman",
        "Cavalier",
        "Chafed Cherry",
        "Chainsaw",
        "Chef's Hat",
        "Cherry Top",
        "Clamshell",
        "Cockroach",
        "Cow Skull",
        "Cromulon",
        "Day of the Tentacle",
        "deadmau5",
        "Deerstalker",
        "Derby",
        "Devil Horns",
        "Dizzy Birds",
        "Dragon Wings",
        "Drink Helmet",
        "Drip Drop",
        "Easter Basket",
        "Fallen Tree",
        "Fez",
        "Fire Helmet",
        "Fishbowl",
        "Foam Hat",
        "Fruit Hat",
        "Gargoyle",
        "GG the Clown",
        "Ghost",
        "Gold Cap",
        "Goldfish",
        "Graduation Cap",
        "Grave Robber",
        "Great White",
        "Halo",
        "Happy Penguin",
        "Hard Hat",
        "Hawaiian Lei",
        "Helper Elf",
        "Holiday Bow",
        "Homburg",
        "Hot Wheels Gorilla",
        "Hot Wheels RC Rivals",
        "Hot Wheels Snake",
        "Hot Wheels Spider",
        "Hotcakes",
        "Hustle Brows",
        "Ivy Cap",
        "Jack-in-the-Box",
        "Jolt Bangle I",
        "Jolt Bangle II",
        "Jolt Bangle III",
        "Jurassic Park Hard Hat",
        "Kayak",
        "Latte",
        "LFT",
        "Light Bulb",
        "Little Bow",
        "Little Bunny",
        "Little Cow",
        "Little Dog",
        "Little Elephant",
        "Little Owl",
        "Little Sloth",
        "Locomotive",
        "Macaron",
        "Mariachi Hat",
        "MMS Headphones",
        "Mohawk",
        "Monstercat Uncaged",
        "Mount Champion",
        "Mouse Trap",
        "Mr. Banana",
        "Mr. Hot Dog",
        "Mr. Hot Pepper",
        "Mr. Meeseeks",
        "Mr. PBH",
        "Mr. Pineapple",
        "Octopus",
        "Palm Tree",
        "Paper Boat",
        "Party Hat",
        "Phoenix Wings I",
        "Phoenix Wings II",
        "Phoenix Wings III",
        "Pirate's Hat",
        "Pixelated Shades",
        "Pizza Topper",
        "Plunger",
        "Police Hat",
        "Pork Pie",
        "Portal - Cake",
        "Propellerhead",
        "Pumpkin",
        "Rainbow",
        "Rasta",
        "Rhino Horns",
        "Rooster Comb",
        "Royal Crown",
        "Sad Sapling",
        "Sad Strawberry",
        "Sand Castle",
        "Santa",
        "Scarecrow Jack",
        "Season 1 - Bronze",
        "Season 1 - Gold",
        "Season 1 - Platinum",
        "Season 1 - Silver",
        "Shark Bite",
        "Shark Fin",
        "Shuriken",
        "Snowboards",
        "Sombrero",
        "Stegosaur",
        "Stoic Muffin",
        "Succulents",
        "Surfboard",
        "Sushi Nigiri",
        "Swim Ring",
        "Taxi Topper",
        "Tiara",
        "Top Hat",
        "Traffic Cone",
        "Trucker Hat",
        "Two-Timer",
        "Uncle Sam",
        "Undying Love",
        "Visor",
        "White Hat",
        "Wildcat Ears",
        "Witch's Hat",
        "Wizard Hat",
        "Work Boot",
        "Worms W.M.D.",
        "Worried Watermelon"
    ],
    trails: [
        "'80s Grad",
        "Binary",
        "Blazer",
        "Bossfight",
        "Candy Cane",
        "Carbon Fiber",
        "Cutlass",
        "EKG-OMG",
        "EQ",
        "Friction",
        "Gassy Mexican",
        "Glossy Block",
        "Grass",
        "Guinea Bissau",
        "Hallowtide",
        "Heart Glasses",
        "Hot Rocks",
        "Inverness",
        "Laser Wave I",
        "Laser Wave II",
        "Laser Wave III",
        "Lightspeed",
        "Luminous",
        "Lustrum X10",
        "New Year's 2017",
        "Revenant",
        "ROBO-Visor",
        "Russia",
        "Season 4 - Bronze",
        "Season 4 - Champion",
        "Season 4 - Diamond",
        "Season 4 - Gold",
        "Season 4 - Platinum",
        "Season 4 - Silver",
        "Toon Glossy",
        "Toon Hydro",
        "Toon Wood",
        "Triplex",
        "Woofless",
        "Zigzag"
    ],
    wheels: [
        "Aero Mage",
        "Aether",
        "Alchemist",
        "Almas",
        "Apex",
        "ARA-51",
        "Asterias",
        "Balla-Carrà",
        "Bender",
        "Capacitor I",
        "Capacitor II",
        "Capacitor III",
        "Capacitor IV",
        "Carriage",
        "Cauldron",
        "Centro",
        "Chakram",
        "Christmas Wreath",
        "Chrono",
        "Clockwork",
        "COG",
        "Cristiano",
        "Cruxe",
        "Decennium Pro",
        "Diablo",
        "Dieci",
        "Diomedes",
        "Discotheque",
        "Doughnut",
        "Draco",
        "Dynamo",
        "Equalizer",
        "Falco",
        "FGSP",
        "Fireplug",
        "Foreman",
        "FSL",
        "GA-819 HB",
        "Gaiden",
        "Gearlock",
        "Goldstone",
        "Grimalkin",
        "Hikari P5",
        "Hiro",
        "Hot Hot Wheels", 
        "Hypnotik",
        "Illuminata",
        "Infinium",
        "Invader",
        "K2",
        "Kalos",
        "Kyrios",
        "Libertine",
        "Lobo",
        "Looper",
        "Lowrider",
        "Lucci",
        "Mario NSR",
        "Masato",
        "Meridian",
        "Mothership Pro",
        "Mountaineer",
        "Neptune",
        "Ninja",
        "Nipper",
        "Octavian",
        "OEM",
        "OH5",
        "Peppermint",
        "Photon",
        "Pinwheel",
        "Pulsus",
        "Puma",
        "Pyramidia",
        "Quimby",
        "Rat Rod",
        "Razzle",
        "Reactor",
        "REEVRB",
        "Rhino",
        "Roulette",
        "Sanchez DC-137",
        "Santa Fe",
        "Saptarishi",
        "SARPBC-10",
        "Season 3 - Challenger",
        "Season 3 - Champion",
        "Season 3 - Prospect",
        "Season 3 - Star",
        "Season 6 - Bronze",
        "Season 6 - Champion",
        "Season 6 - Diamond",
        "Season 6 - Gold",
        "Season 6 - Platinum",
        "Season 6 - Silver",
        "Septem",
        "Servergate",
        "SLK",
        "Sovereign A/T",
        "Sovereign Pro",
        "Spinner",
        "Spiralis",
        "Spyder",
        "Stallion",
        "Stern",
        "Tempest",
        "Thread-X2",
        "Tomahawk",
        "Trahere",
        "Troika",
        "Troublemaker I",
        "Troublemaker II",
        "Troublemaker III",
        "Troublemaker IV",
        "Tunica",
        "Turbine",
        "Veloce",
        "Voltaic",
        "Vortex",
        "Watermelon",
        "Wonderment",
        "WW5SP",
        "Yuzo",
        "Zeta",
        "Zomba",
        "Z-Plate",
        "ZT-17"     
    ]
}
